# Generated by Django 5.2.1 on 2025-11-26 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('data_sorteio', models.DateField(blank=True, null=True)),
                ('valor_limite', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('grupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='administradores', to='amigo_secreto.grupo')),
            ],
        ),
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('login', models.CharField(max_length=50, unique=True)),
                ('lista_desejos', models.JSONField(default=list)),
                ('grupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participantes', to='amigo_secreto.grupo')),
                ('resultado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quem_tirou', to='amigo_secreto.participante')),
            ],
        ),
        migrations.CreateModel(
            name='ListaDesejos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=200)),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listas', to='amigo_secreto.participante')),
            ],
        ),
        migrations.CreateModel(
            name='Sorteio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foi_tirado_por', to='amigo_secreto.participante')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sorteios', to='amigo_secreto.grupo')),
                ('quem_tirou', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quem_tirou_no_grupo', to='amigo_secreto.participante')),
            ],
        ),
    ]
